import json
with open(r"C:\Users\Prash\Desktop\SAST\backend\_finding2.json") as f:
    d = json.load(f)
print("finding_id:", d["finding_id"])
print("vuln_type:", d["vulnerability_type"])
print("severity:", d["severity"])
print("repo:", d.get("repository"))
print("project_id:", d.get("project", {}).get("project_id"))
print("project_name:", d.get("project", {}).get("name"))
print()
print("source_file:", d["source"]["file"])
print("source_line:", d["source"]["line"])
print("source_snippet:", d["source"]["snippet"])
print()
print("sink_file:", d["sink"]["file"])
print("sink_line:", d["sink"]["line"])
print("sink_snippet:", d["sink"]["snippet"])
print()
print("validation:", d.get("validation", {}).get("verdict") if d.get("validation") else "NONE")
print("proof:", d.get("proof", {}).get("status") if d.get("proof") else "NONE")
print("approval:", d.get("approval", {}).get("status") if d.get("approval") else "NONE")
print("remediation:", d.get("remediation", {}).get("status") if d.get("remediation") else "NONE")
print()
print("taint_path:")
for step in d.get("taint_path", []):
    print(f'  L{step["line"]}: [{step["step_type"]}] {step["snippet"]}')
