"""SandboxRunner: isolated execution of approved proof harnesses.

Safety properties enforced here:

* a fresh temporary workspace is created per run (and removed afterwards);
* ONLY approved harness scripts (``APPROVED_HARNESSES``) may be executed -
  the harness code is always generated by the trusted planner templates,
  never taken from the repository;
* the repository's own entrypoints are never executed;
* hard timeout kills the harness process;
* stdout/stderr are truncated to ``max_output_bytes``;
* exactly one subprocess is spawned (``max_processes=1``);
* each harness asserts it runs inside the sandbox workspace
  (``SANDBOX_DIR``) before doing anything.

Platform limitation (documented): on a plain host this is a *soft* sandbox -
the OS-level jail is the temp workspace plus the policy the harnesses
themselves enforce. OS-level network blocking (firewall, seccomp) is not
applied; instead the approved harnesses never touch the network by
construction (the only socket in the SSRF harness binds loopback ephemeral
in-process), and ``network_enabled`` stays False for every proof.
"""

import os
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass

from app.prove.models import SandboxPolicy
from app.prove.planner import APPROVED_HARNESSES, HARNESS_SCRIPTS

_TRUNCATE_SUFFIX = "\n...[output truncated by sandbox policy]..."


class SandboxViolation(RuntimeError):
    """Raised when a harness or call is not allowed by the sandbox."""


@dataclass
class ExecutionResult:
    returncode: int | None
    stdout: str
    stderr: str
    timed_out: bool
    truncated: bool
    workspace: str  # deleted after cleanup; kept for diagnostics/policy record


class SandboxRunner:
    def __init__(self, policy: SandboxPolicy | None = None) -> None:
        self.policy = policy or SandboxPolicy()

    def run(
        self,
        harness_name: str,
        script: str,
        *args: str,
        env: dict[str, str] | None = None,
        policy: SandboxPolicy | None = None,
    ) -> ExecutionResult:
        """Execute one approved harness inside a fresh sandbox workspace.

        ``policy`` (when given) overrides the runner's default for this run;
        the temporary workspace is always added to ``allowed_paths``.
        """
        if harness_name not in APPROVED_HARNESSES:
            raise SandboxViolation(f"harness {harness_name!r} is not approved")
        expected = HARNESS_SCRIPTS[harness_name]()
        if script != expected:
            raise SandboxViolation(
                f"harness script for {harness_name!r} does not match the trusted template"
            )

        effective = (policy or self.policy).model_copy(
            update={
                "temporary_directory": "",
                "allowed_paths": [],
            }
        )
        workspace = tempfile.mkdtemp(prefix="sast_prove_")
        self.policy = effective.model_copy(
            update={
                "temporary_directory": workspace,
                "allowed_paths": [workspace] + effective.allowed_paths,
            }
        )
        script_path = os.path.join(workspace, f"{harness_name}.py")
        with open(script_path, "w", encoding="utf-8") as fh:
            fh.write(script)

        run_env = dict(os.environ)
        run_env["SANDBOX_DIR"] = workspace
        if env:
            run_env.update(env)

        truncated = False
        try:
            try:
                proc = subprocess.run(
                    [sys.executable, script_path, *args],
                    cwd=workspace,
                    env=run_env,
                    capture_output=True,
                    text=True,
                    timeout=self.policy.timeout_seconds,
                )
                stdout, stderr = self._truncate(proc.stdout), self._truncate(proc.stderr)
                if len(proc.stdout) > self.policy.max_output_bytes:
                    truncated = True
                return ExecutionResult(
                    returncode=proc.returncode,
                    stdout=stdout,
                    stderr=stderr,
                    timed_out=False,
                    truncated=truncated,
                    workspace=workspace,
                )
            except subprocess.TimeoutExpired as exc:
                stdout = self._truncate(exc.stdout or "")
                stderr = self._truncate(exc.stderr or "")
                if len(exc.stdout or "") > self.policy.max_output_bytes:
                    truncated = True
                return ExecutionResult(
                    returncode=None,
                    stdout=stdout,
                    stderr=stderr,
                    timed_out=True,
                    truncated=truncated,
                    workspace=workspace,
                )
        finally:
            shutil.rmtree(workspace, ignore_errors=True)

    # ---------------------------------------------------------------- helpers

    def _truncate(self, text: str) -> str:
        limit = self.policy.max_output_bytes
        if len(text) <= limit:
            return text
        return text[:limit] + _TRUNCATE_SUFFIX
